import { Issue } from '../types';

// Values generated by humanizeRule() and humanizeDescription() in payloadNormalization.ts.
// These are local fallbacks, not real PPOS data — treat as generic and skip them
// so we fall through to the code map or the actual PPOS-provided message.
const GENERIC_PLACEHOLDERS = new Set([
    // System placeholders
    'Technical preflight finding',
    'System deviation detected.',
    // humanizeRule() outputs
    'Geometry Violation',
    'Typography Incompatibility',
    'Color Space Deviation',
    'Dimension Mismatch',
    'Image Quality Alert',
    'Bleed Margin Warning',
    'Trim Box Anomaly',
    'PDF Version Deviation',
    'Font Embedding Issue',
    'Rich Black Overload',
    'Spot Color Alert',
    // humanizeDescription() outputs
    'The document contains geometry variations that may affect centering and alignment during the printing process.',
    'One or more fonts or text elements appear legacy or incompatible with the target print profile, which could cause rendering errors.',
    'A color space deviation was detected. Some elements may use RGB or non-standard profiles that will shift when converted.',
    'The page boundary boxes (Trim, Bleed, Media) are inconsistent or missing, which is critical for automated imposition.',
    'Some graphical assets have a resolution lower than the 300 DPI industry standard, risking pixelation.',
    'No bleed margins were detected. Background elements end exactly at the trim line, creating a risk of white edges after cutting.',
    'The trim box is not correctly defined or is too close to critical content, which may result in content loss.',
    'The PDF version or structure does not strictly follow the PDF/X output intent standard.',
    'There are non-embedded fonts in the file. The printer may substitute them with generic typefaces.',
    'Some black elements use a total ink coverage above 320%, which may cause smearing or drying issues.',
    'Document uses spot colors (Pantones) that are not part of the standard CMYK target process.',
]);

/**
 * Returns the most specific human-readable title for an issue.
 * Normalizes known Spanish titles to English keys first, then prefers
 * the specific title from PPOS/normalization, falling back to code-based
 * category labels when no specific title is available.
 */
export const translateIssueTitle = (issue: Issue | null | undefined, t: (key: string) => string): string => {
    if (!issue) return "Unknown Finding";

    // 1. Normalize known Spanish titles to English keys (PPOS may send Spanish)
    if (issue.title?.includes('marcas de corte') || issue.message?.includes('marcas de corte')) {
        return t('finding.trim_anomaly');
    }
    if (issue.title?.includes('Uso de RGB') || issue.message?.includes('Uso de RGB') || issue.title?.includes('perfiles no estándar')) {
        return t('finding.color_compliance');
    }

    // Raw codes (all-caps + underscores, no spaces) are not human-readable — skip them.
    const CODE_PATTERN = /^[A-Z][A-Z0-9_]*$/;

    // 2. Prefer specific title from PPOS if it's human-readable and not a local fallback.
    if (issue.title && !GENERIC_PLACEHOLDERS.has(issue.title) && !CODE_PATTERN.test(issue.title)) {
        return issue.title;
    }

    // 3. Use the message field — same source the slide-over shows as "Finding Details".
    const msg = issue.message || issue.user_message;
    if (msg && !GENERIC_PLACEHOLDERS.has(msg) && !CODE_PATTERN.test(msg)) {
        return msg;
    }

    const code = (issue.code || issue.id || "").toString().toUpperCase();

    // 4. Code-based category labels as last resort — prefix-matched so IND_GEOM_002 resolves to IND_GEOM, etc.
    const codes: Record<string, string> = {
        'IND_GEOM': t('finding.geom_anomaly'),
        'IND_TYPE': t('finding.typography_integrity'),
        'IND_COLOR': t('finding.color_compliance'),
        'IND_BOX': t('finding.trim_anomaly'),
        'IND_IMAGE': t('finding.image_analysis'),
        'IND_BLEED': t('finding.bleed_exception'),
        'IND_TRIM': t('finding.trim_anomaly'),
        'IND_FONT': t('finding.typography_integrity'),
        'IND_BLACK': t('finding.ink_limit_violation'),
        'IND_SPOT': t('finding.spot_color_warning'),
        'IND_PDF': t('finding.pdf_compliance_error'),
        'IND_IMG': t('finding.image_analysis'),
        'IND_RESOLUTION': t('finding.resolution_fault'),
        'IND_METADATA': t('finding.metadata_fault'),
        'IND_TRANSPARENCY': t('finding.transparency_risk'),
        'IND_COMPLIANCE': t('finding.compliance_violation'),
        'IND_STRUCT': t('finding.structure_fault'),
        'TRIM_BOX_MISSING': t('finding.trim_anomaly'),
        'COLOR_RGB': t('finding.rgb_detected'),
        'IMAGE_LOW_RES': t('finding.low_res_asset'),
        'FONT_NOT_EMBEDDED': t('finding.unembedded_glyph'),
        'BLEED_MISSING': t('finding.bleed_exception'),
        'INTENT_BOOK': t('finding.book_intent'),
        'HEURISTIC_TEXT_OUTLINED': t('finding.text_outlined'),
    };

    // Exact match first, then prefix match (handles sub-codes like IND_COMPLIANCE_001)
    if (codes[code]) return codes[code];
    for (const [prefix, label] of Object.entries(codes)) {
        if (code.startsWith(prefix + '_') || code.startsWith(prefix + '-')) return label;
    }

    return t('finding.critical_trace');
};

/**
 * Phase APP-40.5 — No-Autofix Policy Enforcement.
 *
 * These categories of findings are knowingly NOT reliable autofixes — the engine
 * cannot apply them deterministically without human/customer involvement. They must
 * be presented as diagnostic-only / reupload-recommended / operator-review-required,
 * never as "Magic Fix available", "Production certified", or "Fixed automatically".
 */
export type NoAutofixPolicyClassification = 'diagnostic_only' | 'customer_reupload_recommended' | 'operator_review_required' | null;

const NO_AUTOFIX_REPAIR_STRATEGIES = new Set([
    'REBUILD_300DPI',
    'UPSCALE_LOW_RESOLUTION',
    'REPAIR_JPEG_ARTIFACTS',
    'RASTER_TO_VECTOR',
    'RECOVER_MISSING_GLYPHS',
    'SUBSTITUTE_FONTS',
    'CONVERT_PDFX',
    'CONVERT_PDFA',
    'CORRECT_TAC',
]);

const REUPLOAD_RECOMMENDED_STRATEGIES = new Set([
    'REBUILD_300DPI',
    'UPSCALE_LOW_RESOLUTION',
    'REPAIR_JPEG_ARTIFACTS',
    'RASTER_TO_VECTOR',
    'RECOVER_MISSING_GLYPHS',
]);

const NO_AUTOFIX_KEYWORDS: Array<{ pattern: RegExp; classification: NoAutofixPolicyClassification }> = [
    { pattern: /low[- ]res(olution)?\s*upscal|upscal.*image/i, classification: 'customer_reupload_recommended' },
    { pattern: /jpeg artifact|jpg artifact/i, classification: 'customer_reupload_recommended' },
    { pattern: /raster.*(to )?vector|vectoriz/i, classification: 'customer_reupload_recommended' },
    { pattern: /missing glyph|glyph recovery/i, classification: 'customer_reupload_recommended' },
    { pattern: /font substitution|substitute font/i, classification: 'operator_review_required' },
    { pattern: /pdf\/x conversion|convert.*pdf\/x/i, classification: 'operator_review_required' },
    { pattern: /pdf\/a conversion|convert.*pdf\/a/i, classification: 'operator_review_required' },
    { pattern: /\btac\b.*correction|total ink coverage correction/i, classification: 'operator_review_required' },
    { pattern: /300\s*dpi rebuild|rebuild.*300\s*dpi/i, classification: 'diagnostic_only' },
];

/**
 * Classifies an issue/fix against the no-autofix policy. Returns `null` when the
 * issue is a normal, reliably-autofixable finding (no special handling needed).
 */
export function classifyNoAutofixPolicy(issue: any): NoAutofixPolicyClassification {
    if (!issue) return null;

    const strategy = (issue.repairStrategy || issue.fix_method || '').toString().toUpperCase();
    if (strategy) {
        if (REUPLOAD_RECOMMENDED_STRATEGIES.has(strategy)) return 'customer_reupload_recommended';
        if (NO_AUTOFIX_REPAIR_STRATEGIES.has(strategy)) return 'diagnostic_only';
    }

    const haystack = [issue.title, issue.message, issue.description]
        .filter(Boolean)
        .join(' ')
        .toLowerCase();

    for (const { pattern, classification } of NO_AUTOFIX_KEYWORDS) {
        if (pattern.test(haystack)) return classification;
    }

    return null;
}

export const NO_AUTOFIX_POLICY_LABELS: Record<Exclude<NoAutofixPolicyClassification, null>, string> = {
    diagnostic_only: 'Diagnostic only',
    customer_reupload_recommended: 'Customer reupload recommended',
    operator_review_required: 'Operator review required',
};
