const fs = require('fs');
const path = require('path');

const resultsLog = path.join(__dirname, '..', 'stress_results.jsonl');
const reportPath = path.join(__dirname, '..', 'stress_test_results.md');

function generateReport() {
    if (!fs.existsSync(resultsLog)) {
        console.error('No results found.');
        return;
    }

    const lines = fs.readFileSync(resultsLog, 'utf8').trim().split('\n');
    const results = lines.map(l => JSON.parse(l));

    const total = results.length;
    const successes = results.filter(r => r.status === 'SUCCESS');
    const failures = results.filter(r => r.status === 'FAILED');

    const durations = results.map(r => r.duration).sort((a, b) => a - b);
    const p50 = durations[Math.floor(total * 0.5)];
    const p95 = durations[Math.floor(total * 0.95)];
    const p99 = durations[Math.floor(total * 0.99)];

    const errorCounts = {};
    failures.forEach(f => {
        const msg = f.error || 'Unknown Error';
        errorCounts[msg] = (errorCounts[msg] || 0) + 1;
    });

    const report = `
# Industrial Stress-Test Results

**Date**: ${new Date().toISOString()}
**Volume**: ${total} PDFs

## Core Metrics
| Metric | Value |
| :--- | :--- |
| **Total Requests** | ${total} |
| **Success Rate** | ${((successes.length / total) * 100).toFixed(2)}% |
| **P50 Latency** | ${p50}ms |
| **P95 Latency** | ${p95}ms |
| **P99 Latency** | ${p99}ms |

## Error Distribution
${Object.entries(errorCounts).length > 0 ?
            Object.entries(errorCounts).map(([err, count]) => `- **${err}**: ${count}`).join('\n') :
            'No errors detected.'}

## Infrastructure Health (Analysis)
- **Redis Stability**: ${failures.some(f => f.error?.includes('Redis')) ? '⚠️ Issues detected' : '✅ Stable'}
- **Ghostscript Concurrency**: ${p99 > p50 * 5 ? '⚠️ Possible slot saturation' : '✅ Optimized'}
- **Postgres Latency**: ${results.some(r => r.duration > 10000) ? '⚠️ High duration detected' : '✅ Normal'}

---
*Generated by PrintPrice Stress Monitor*
`;

    fs.writeFileSync(reportPath, report);
    console.log(`[STRESS-MONITOR] Report generated at ${reportPath}`);
}

generateReport();
